#source 'https://git.cisdigital.cn/jun.d.yang/Specs.git'

platform :ios, '12.0'
use_frameworks!
#install! 'cocoapods', :disable_input_output_paths => true

# 配置需要打包的库
$frameworks = ['HandyJSON']

target 'Archive' do
  # 引入库
  pod 'HandyJSON', '~> 5.0.2'
end

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {
  }
end

post_install do |installer|
  project = installer.pods_project
  project.recreate_user_schemes(:visible => true)
  project.save
  project.targets.each do |target|
    target.build_configurations.each do |config|
      #config.build_settings['VALID_ARCHS[sdk=iphonesimulator*]'] = 'x86_64' # 模拟器
      config.build_settings['ARCHS'] = 'arm64' # 64位
      config.build_settings["DEVELOPMENT_TEAM"] = "7BT4LD3H35" # 项目ID
      config.build_settings['SUPPORTED_PLATFORMS'] = 'iphoneos' # 只打手机包
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'NO' # NO开启警告提示
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['ENABLE_BITCODE'] = 'YES' # 是否开启 BITCODE
#      config.build_settings['SWIFT_SERIALIZE_DEBUGGING_OPTIONS'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#      config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -Xfrontend -no-serialize-debugging-options'
    end
    if $frameworks.include?(target.name)
      puts "share #{target.name}"
      Xcodeproj::XCScheme.share_scheme(installer.sandbox.project_path, target)
    end
  end
end

