platform :ios, '9.0'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

# 配置需要打包的库
$frameworks = ['Alamofire']

target 'Archive' do
    # 引入库
    pod 'Alamofire'
end

post_install do |installer|
    project = installer.pods_project
    project.recreate_user_schemes(:visible => true)
    project.save
    project.targets.each { |target|
        if $frameworks.include?(target.name)
            Xcodeproj::XCScheme.share_scheme(installer.sandbox.project_path, target)
        end
    }
end
