# This file contains the fastlane.tools configuration
# https://docs.fastlane.tools/actions/cocoapods/
# https://docs.fastlane.tools/actions/carthage/

#update_fastlane
default_platform(:ios)

platform :ios do

    desc "pod 打包"
    lane :archive do
        sh('rm -rf ../Carthage/Build/iOS')
        sh('rm -rf ../Archive/Pods/Pods.xcodeproj/xcshareddata')
        cocoapods(podfile: "./Archive/Podfile")
        sh('rm -rf ../Archive/Pods/Pods.xcodeproj/xcuserdata')
        carthage(
            command: "build", 
            use_binaries: true,
            no_skip_current: true,
            verbose: true,
            platform: "iOS",
            configuration: "Release",
            cache_builds: true
        )
        sh('open ../Carthage/Build/iOS')        
    end

end

